### ISSUE TITLE
Feat: incorporate EMX for Variant module

### ISSUE THREAD

**Issue by davidruvolo51** [molgenis/rd-datamodel#13]
## New Variant Classification Module

We would like to create a module for capturing variant information. Using the existing variants project as a starting point, create a module...

- [ ] where attributes follow the same naming format as the rest of the model. e.g., `belongsTo...`, `reasonFor...`, etc.
- [ ] that includes semantic tags for variant attributes 
- [ ] and lookup tables relevant to the new variant table

### Tasks

- [ ] convert existing model to yaml format
- [ ] harmonize attribute names
- [ ] add semantic tags
- [ ] create lookups

**Comment by davidruvolo51** [comment]
I'm closing this issue for now as this feature will be implemented in another way. At some point we may revisit this, but there aren't any plans to work on this.
